### ISSUE TITLE
Repository URL in installation instructions is outdated

### ISSUE THREAD

**Issue by schoinh** [AllenCell/aics-segmentation#13]
## Description
In the installation docs for MacOS, Linux, and Windows, the URL provided in the code snippet for `git clone` points to an outdated repository:

```
git clone https://github.com/AllenInstitute/aics-segmentation.git
```

## Expected Behavior
The markdown files should say:
```
git clone https://github.com/AllenCell/aics-segmentation.git
```

**Comment by jxchen01** [comment]
fixed in #25
