### ISSUE TITLE
Lookup table link in jupyter_lookup_table.md gives 404 error

### ISSUE THREAD

**Issue by schoinh** [AllenCell/aics-segmentation#15]
## Description
In the first paragraph of the ["Documentation for Users" doc](https://github.com/AllenCell/aics-segmentation/blob/main/docs/jupyter_lookup_table.md#documentation-for-users), there is a link to a lookup table. Following the link gives a 404 error.
![image](https://user-images.githubusercontent.com/12690133/107838067-fc289600-6d58-11eb-8a76-f56a6ca4969b.png)

## Expected Behavior
Clicking the link should lead me to the lookup table.

**Comment by raiblelab** [comment]
The link 
https://github.com/AllenCell/aics-segmentation/blob/main/docs/www.allencell.org/segmenter.html#lookup-table
should be
https://www.allencell.org/segmenter.html#lookup-table

**Comment by jxchen01** [comment]
this has been fixed in #24
