### ISSUE TITLE
Demo notebook does not run: IMG.Shape yields 6 dimensions, not 5

### ISSUE THREAD

**Issue by raiblelab** [AllenCell/aics-segmentation#22]
## Description
*A clear description of the bug*
I ran the demo_TNNI1.ipynb notebook using the TNNI1_demo_data.tif provided in the demo_data folder.

In Cell 2 of the demo notebooks, IMG shape yields a tuple with 6 elements, however the rest of the notebook expects 5 elements.  

As a consequence, all further cells fail to run.
## Expected Behavior
*What did you expect to happen instead?*

## Reproduction
*A minimal example that exhibits the behavior.*

<img width="1055" alt="Screen Shot 2021-03-03 at 12 53 36 PM" src="https://user-images.githubusercontent.com/79722030/109870953-87da6780-7c1f-11eb-9457-96a26889326b.png">

## Environment
*Any additional information about your environment*

It looks like the output dimensions of AICSImage changed with aicsimageio 3.0.7 to 3.1.0

**Comment by jxchen01** [comment]
Thanks for reporting this. I will release an update later tonight. 

Thanks again.
Jianxu

**Comment by raiblelab** [comment]
Thanks for your work on this package!

Here are the changes I made to make it work (in bold):

In Cell 3:

N_CHANNELS = IMG.shape[2]
MID_SLICE = int(0.5*IMG.shape[3])

fig, ax = plt.subplots(1, N_CHANNELS, figsize=(18,16), dpi=72, facecolor='w', edgecolor='k')
if N_CHANNELS==1:
    ax.axis('off')
    ax.imshow(IMG[0,0,0,MID_SLICE,:,:], cmap=plt.cm.gray)
else:
    for channel in range(N_CHANNELS):
        ax[channel].axis('off')
        ax[channel].imshow(IMG[0,0,channel,MID_SLICE,:,:], cmap=plt.cm.gray)

In Cell 4:

#####################
structure_channel = 1
#####################

struct_img0 = IMG[0,0,structure_channel,:,:,:].copy()
view(single_fluorescent_view(struct_img0))

**Comment by jxchen01** [comment]
thanks, this has been fixed in #24
