### ISSUE TITLE
Adjust intensity normalization scaling params

### ISSUE THREAD

**Issue by schoinh** [AllenCell/aics-segmentation#65]
Requested by @derekthirstrup on Slack: https://allencellscience.slack.com/archives/C01L7L5M29H/p1625862584147500

## Use Case
As a segmenter plugin user, I can't replicate a terf2 pipeline script since intensity normalization does not allow 0.25 as a value in the napari segmenter plugin ui. 

## Solution
* The lower limit for the Intensity Normalization scaling param (both sliders) should be 0 instead of 0.5. 
* Add a couple sig figures to the adjustable incremental display values

**Comment by schoinh** [comment]
@jxchen01 Is this ok to do? Who else can we ask for an OK on things like this?

**Comment by jxchen01** [comment]
Suppose the lower limit is A and upper limit is B, and suppose mean intensity and standard deviation of the image is M and S. In theory, A and B can be any value, as long as M - A * S < M + B * S. 

What we will do: 
- allow wider range of lower and upper limit, including negative values
- add assertion to make sure M - A * S < M + B * S

Benji and I are OOO this week. We will make a PR to fix this asap next week. Benji will be back on Monday, I will be back on Wednesday.
